# Generated by Django 3.2.9 on 2021-12-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apeliido',
            new_name='apellido',
        ),
    ]
